$ErrorActionPreference = 'Stop'

$hise      = 'C:\Program Files\HISE.exe'
$proj      = 'E:\个人EQ项目\编码\AnalogBlend'
$hisePath  = 'E:\个人EQ项目\编码\HISE'
$projucer  = "$hisePath\tools\Projucer\Projucer.exe"
$msbuild   = 'C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\MSBuild.exe'
$vst3Out   = "$proj\Binaries\Compiled\VST3\Analog Blend.vst3"
$vst3Dest  = 'E:\VST3\ReiVerb Work Shop\BK_EQ_Hybrid.vst3'

Write-Host '== 1/5 HISE 导出（生成工程与资源） ==' -ForegroundColor Cyan
& $hise set_hise_folder -p:$hisePath | Out-Null
& $hise set_project_folder -p:$proj | Out-Null
# CI 模式不运行自带 batch（避免异步 Projucer 竞态），但它从 exe 所在目录向上找 hi_core，
# 因此把 HISE.exe 复制到 SDK 根目录旁再调用
Copy-Item -LiteralPath $hise -Destination "$hisePath\HISE.exe" -Force
Push-Location $proj
& "$hisePath\HISE.exe" export_ci "XmlPresetBackups\AnalogBlend.xml" -t:effect -p:VST3 -a:x64 -nolto 2>&1 | Out-String | Write-Output
Pop-Location
# 校验导出产物（不加管道时 HISE 可能提前返回）
if (-not (Test-Path "$proj\Binaries\Source\PresetData.cpp") -or (Get-Item "$proj\Binaries\Source\PresetData.cpp").Length -lt 1000000) { throw '导出未完成：PresetData.cpp 缺失或过小' }
if ((Get-Item "$proj\Binaries\Source\PresetData.h").Length -lt 100) { throw '导出未完成：PresetData.h 为空' }

Write-Host '== 2/5 修正 .jucer（关闭 IPP） ==' -ForegroundColor Cyan
$jucer = "$proj\Binaries\AutogeneratedProject.jucer"
(Get-Content $jucer -Raw) -replace 'USE_IPP="1"', 'USE_IPP="0"' | Set-Content $jucer -Encoding UTF8

Write-Host '== 3/5 Projucer 重新生成 VS 工程 ==' -ForegroundColor Cyan
Start-Process -FilePath $projucer -ArgumentList @('--resave', "`"$jucer`"") -WindowStyle Hidden -Wait

Write-Host '== 4/5 补丁：v145 工具集 + 关闭 VST2 兼容宏 ==' -ForegroundColor Cyan
$shared = "$proj\Binaries\Builds\VisualStudio2022\Analog Blend_SharedCode.vcxproj"
$vst3pr = "$proj\Binaries\Builds\VisualStudio2022\Analog Blend_VST3.vcxproj"
foreach ($f in @($shared, $vst3pr))
{
    $c = Get-Content $f -Raw
    $c = $c -replace '<PlatformToolset>v143</PlatformToolset>', '<PlatformToolset>v145</PlatformToolset>'
    Set-Content $f -Value $c -Encoding UTF8
}
foreach ($f in @($shared, $vst3pr))
{
    if (Get-Content $f -Raw | Select-String -Quiet 'v143')
    {
        $c = Get-Content $f -Raw
        $c = $c -replace '<PlatformToolset>v143</PlatformToolset>', '<PlatformToolset>v145</PlatformToolset>'
        Set-Content $f -Value $c -Encoding UTF8
    }
    if (Get-Content $f -Raw | Select-String -Quiet 'v143') { throw "补丁未生效：$f" }
}
$c = Get-Content $vst3pr -Raw
$c = $c -replace 'JucePlugin_Build_Unity=0;', 'JucePlugin_Build_Unity=0;JUCE_VST3_CAN_REPLACE_VST2=0;'
Set-Content $vst3pr -Value $c -Encoding UTF8
if (-not (Get-Content $vst3pr -Raw | Select-String -Quiet 'JUCE_VST3_CAN_REPLACE_VST2=0')) { throw 'VST2 宏补丁未生效' }

Write-Host '== 5/5 编译（MSBuild） ==' -ForegroundColor Cyan
& $msbuild "$proj\Binaries\Builds\VisualStudio2022\Analog Blend.sln" /p:Configuration=Release /p:Platform=X64 /m /v:minimal
if ($LASTEXITCODE -ne 0) { throw 'MSBuild 编译失败' }

Copy-Item -LiteralPath $vst3Out -Destination $vst3Dest -Force
Write-Host "完成：$vst3Out" -ForegroundColor Green
Write-Host "已安装：$vst3Dest" -ForegroundColor Green




